version: "3.1"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: idat_sqlserver2019
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123456
    volumes:
      - ./database:/var/opt/mssql/data
    networks:
      - fullstack
  backend:
    container_name: idat_backend
    build: ./backend/SolCrudIdat
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
    networks:
      - fullstack
networks:
  fullstack: